use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, sqlx::FromRow)]
pub struct ResumeMedis {
    pub no_rawat: String,
    pub kd_dokter: String,
    pub diagnosa_awal: String,
    pub alasan: String,
    pub keluhan_utama: String,
    pub pemeriksaan_fisik: String,
    pub jalannya_penyakit: String,
    pub pemeriksaan_penunjang: String,
    pub hasil_laborat: String,
    pub tindakan_dan_operasi: String,
    pub obat_di_rs: String,
    pub diagnosa_utama: String,
    pub kd_diagnosa_utama: String,
    pub diagnosa_sekunder: String,
    pub kd_diagnosa_sekunder: String,
    pub diagnosa_sekunder2: String,
    pub kd_diagnosa_sekunder2: String,
    pub diagnosa_sekunder3: String,
    pub kd_diagnosa_sekunder3: String,
    pub diagnosa_sekunder4: String,
    pub kd_diagnosa_sekunder4: String,
    pub prosedur_utama: String,
    pub kd_prosedur_utama: String,
    pub prosedur_sekunder: String,
    pub kd_prosedur_sekunder: String,
    pub prosedur_sekunder2: String,
    pub kd_prosedur_sekunder2: String,
    pub prosedur_sekunder3: String,
    pub kd_prosedur_sekunder3: String,
    pub alergi: String,
    pub diet: String,
    pub lab_belum: String,
    pub edukasi: String,
    pub cara_keluar: String,
    pub ket_keluar: String,
    pub keadaan: String,
    pub ket_keadaan: String,
    pub dilanjutkan: String,
    pub ket_dilanjutkan: String,
    pub kontrol: String,
    pub obat_pulang: String,
}
