use serde::{Deserialize, Serialize};

#[derive(Debug, Deserialize, Serialize)]
pub struct SoapRequest {
    pub keluhan: String,
    pub pemeriksaan: String,
    pub alergi: String,
    pub suhu: String,
    pub tensi: String,
    pub nadi: String,
    pub respirasi: String,
    pub spo2: String,
    pub berat: String,
    pub tinggi: String,
    pub lingkar_perut: String,
    pub lingkar_kepala: String,
    pub lingkar_dada: String,
    pub gcs: String,
    pub kesadaran: String,
    pub penilaian: String,
    pub tindak_lanjut: String,
    pub instruksi: String,
    pub evaluasi: String,
    pub nip: Option<String>,
}

#[derive(Debug, Serialize, sqlx::FromRow)]
pub struct IcdResult {
    pub kd: String,
    pub nm: String,
}

#[derive(Debug, Serialize)]
pub struct DashboardStats {
    pub total_pasien: i64,
    pub rawat_hari_ini: i64,
    pub resep_total: i64,
}

#[derive(Debug, Serialize, sqlx::FromRow)]
pub struct TrendItem {
    pub date: Option<String>,
    pub count: i64,
}

#[derive(Debug, Serialize, sqlx::FromRow)]
pub struct GenderItem {
    pub jk: Option<String>,
    pub count: i64,
}

#[derive(Debug, Serialize, sqlx::FromRow)]
pub struct StatusItem {
    pub stts: Option<String>,
    pub count: i64,
}

#[derive(Debug, Serialize)]
pub struct DashboardData {
    pub stats: DashboardStats,
    pub trend: Vec<TrendItem>,
    pub gender: Vec<GenderItem>,
    pub status: Vec<StatusItem>,
}


#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct PemeriksaanRalan {
    pub no_rawat: String,
    pub tgl_perawatan: Option<String>,
    pub jam_rawat: Option<String>,
    pub suhu_tubuh: String,
    pub tensi: String,
    pub nadi: String,
    pub respirasi: String,
    pub tinggi: String,
    pub berat: String,
    pub spo2: String,
    pub gcs: String,
    pub kesadaran: String,
    pub keluhan: String,
    pub pemeriksaan: String,
    pub alergi: String,
    pub lingkar_perut: String,
    pub lingkar_kepala: String,
    pub lingkar_dada: String,
    pub rtl: String,
    pub penilaian: String,
    pub instruksi: String,
    pub evaluasi: String,
    pub nip: String,
}
#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct PenilaianMedisUmum {
    pub no_rawat: String,
    pub tanggal: Option<String>,
    pub kd_dokter: String,
    pub anamnesis: String,
    pub hubungan: String,
    pub keluhan_utama: String,
    pub rps: String,
    pub rpd: String,
    pub rpo: String,
    pub alergi: String,
    pub keadaan: String,
    pub kesadaran: String,
    pub gcs: String,
    pub td: String,
    pub nadi: String,
    pub rr: String,
    pub suhu: String,
    pub bb: String,
    pub tb: String,
    pub bmi: String,
    pub keluhan: String,
    pub kepala: String,
    pub mata: String,
    pub tht: String,
    pub mulut: String,
    pub leher: String,
    pub thoraks: String,
    pub jantung: String,
    pub paru: String,
    pub abdomen: String,
    pub genital: String,
    pub ekstremitas: String,
    pub kulit: String,
    pub ket_fisik: String,
    pub ket_lokalis: String,
    pub penunjang: String,
    pub diagnosis: String,
    pub tata: String,
    pub konsulrujuk: String,
}

#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct PenilaianMedisAnak {
    pub no_rawat: String,
    pub tanggal: Option<String>,
    pub kd_dokter: String,
    pub anamnesis: String,
    pub hubungan: String,
    pub keluhan_utama: String,
    pub rps: String,
    pub rpd: String,
    pub rpo: String,
    pub alergi: String,
    pub keadaan: String,
    pub kesadaran: String,
    pub gcs: String,
    pub td: String,
    pub nadi: String,
    pub rr: String,
    pub suhu: String,
    pub bb: String,
    pub tb: String,
    pub bmi: String,
    pub keluhan: String,
    pub kepala: String,
    pub mata: String,
    pub gigi: String,
    pub tht: String,
    pub thoraks: String,
    pub abdomen: String,
    pub genital: String,
    pub ekstremitas: String,
    pub kulit: String,
    pub ket_fisik: String,
    pub ket_lokalis: String,
    pub penunjang: String,
    pub diagnosis: String,
    pub tata: String,
    pub konsul: String,
}

#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct PenilaianMedisKandungan {
    pub no_rawat: String,
    pub tanggal: Option<String>,
    pub kd_dokter: String,
    pub anamnesis: String,
    pub hubungan: String,
    pub keluhan_utama: String,
    pub rps: String,
    pub rpd: String,
    pub rpo: String,
    pub alergi: String,
    pub keadaan: String,
    pub kesadaran: String,
    pub gcs: String,
    pub td: String,
    pub nadi: String,
    pub rr: String,
    pub suhu: String,
    pub bb: String,
    pub tb: String,
    pub bmi: String,
    pub kepala: String,
    pub mata: String,
    pub tht: String,
    pub thoraks: String,
    pub abdomen: String,
    pub ekstremitas: String,
    pub kulit: String,
    pub ket_fisik: String,
    pub tfu: String,
    pub tbj: String,
    pub his: String,
    pub kontraksi: String,
    pub djj: String,
    pub inspeksi: String,
    pub inspekulo: String,
    pub vt: String,
    pub rt: String,
    pub ultra: String,
    pub kardio: String,
    pub lab: String,
    pub diagnosis: String,
    pub tata: String,
    pub konsul: String,
}

#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct PenilaianMedisBedah {
    pub no_rawat: String,
    pub tanggal: Option<String>,
    pub kd_dokter: String,
    pub anamnesis: String,
    pub hubungan: String,
    pub keluhan_utama: String,
    pub rps: String,
    pub rpd: String,
    pub rpo: String,
    pub alergi: String,
    pub keadaan: String,
    pub kesadaran: String,
    pub gcs: String,
    pub td: String,
    pub nadi: String,
    pub rr: String,
    pub suhu: String,
    pub bb: String,
    pub tb: String,
    pub bmi: String,
    pub kepala: String,
    pub mata: String,
    pub tht: String,
    pub thoraks: String,
    pub abdomen: String,
    pub ekstremitas: String,
    pub kulit: String,
    pub ket_fisik: String,
    pub ket_lokalis: String,
    pub penunjang: String,
    pub diagnosis: String,
    pub tata: String,
    pub konsulrujuk: String,
}

#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct PenilaianMedisTHT {
    pub no_rawat: String,
    pub tanggal: Option<String>,
    pub kd_dokter: String,
    pub anamnesis: String,
    pub hubungan: String,
    pub keluhan_utama: String,
    pub rps: String,
    pub rpd: String,
    pub rpo: String,
    pub alergi: String,
    pub td: String,
    pub nadi: String,
    pub rr: String,
    pub suhu: String,
    pub bb: String,
    pub tb: String,
    pub nyeri: String,
    pub status_nutrisi: String,
    pub kondisi: String,
    pub ket_lokalis: String,
    pub lab: String,
    pub rad: String,
    pub tes_pendengaran: String,
    pub penunjang: String,
    pub diagnosis: String,
    pub diagnosisbanding: String,
    pub permasalahan: String,
    pub terapi: String,
    pub tindakan: String,
    pub tatalaksana: String,
    pub edukasi: String,
}

#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct PenilaianMedisMata {
    pub no_rawat: String,
    pub tanggal: Option<String>,
    pub kd_dokter: String,
    pub anamnesis: String,
    pub hubungan: String,
    pub keluhan_utama: String,
    pub rps: String,
    pub rpd: String,
    pub rpo: String,
    pub alergi: String,
    pub visuskanan: String,
    pub visuskiri: String,
    pub periksakanan: String,
    pub periksakiri: String,
    pub ekskanan: String,
    pub ekskiri: String,
    pub palpebrakanan: String,
    pub palpebrakiri: String,
    pub konjungtivakanan: String,
    pub konjungtivakiri: String,
    pub korneakanan: String,
    pub korneakiri: String,
    pub coakanan: String,
    pub coakiri: String,
    pub pupilkanan: String,
    pub pupilkiri: String,
    pub lensakanan: String,
    pub lensakiri: String,
    pub funduskanan: String,
    pub funduskiri: String,
    pub papilkanan: String,
    pub papilkiri: String,
    pub retinakanan: String,
    pub retinakiri: String,
    pub makulakanan: String,
    pub makulakiri: String,
    pub tiokanan: String,
    pub tiokiri: String,
    pub mbokanan: String,
    pub mbokiri: String,
    pub lab: String,
    pub rad: String,
    pub penunjang: String,
    pub tes: String,
    pub pemeriksaan: String,
    pub diagnosis: String,
    pub diagnosisbdg: String,
    pub permasalahan: String,
    pub terapi: String,
    pub tindakan: String,
    pub edukasi: String,
}

#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct PenilaianMedisNeurologi {
    pub no_rawat: String,
    pub tanggal: Option<String>,
    pub kd_dokter: String,
    pub anamnesis: String,
    pub hubungan: String,
    pub keluhan_utama: String,
    pub rps: String,
    pub rpd: String,
    pub rpo: String,
    pub alergi: String,
    pub keadaan: String,
    pub kesadaran: String,
    pub td: String,
    pub nadi: String,
    pub rr: String,
    pub suhu: String,
    pub gcs: String,
    pub kepala: String,
    pub keterangan_kepala: String,
    pub thoraks: String,
    pub keterangan_thoraks: String,
    pub abdomen: String,
    pub keterangan_abdomen: String,
    pub ekstremitas: String,
    pub keterangan_ekstremitas: String,
    pub columna: String,
    pub keterangan_columna: String,
    pub muskulos: String,
    pub keterangan_muskulos: String,
    pub lainnya: String,
    pub lab: String,
    pub rad: String,
    pub penunjanglain: String,
    pub diagnosis: String,
    pub diagnosis2: String,
    pub permasalahan: String,
    pub terapi: String,
    pub tindakan: String,
    pub edukasi: String,
}

#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct PenilaianMedisParu {
    pub no_rawat: String,
    pub tanggal: Option<String>,
    pub kd_dokter: String,
    pub anamnesis: String,
    pub hubungan: String,
    pub keluhan_utama: String,
    pub rps: String,
    pub rpd: String,
    pub rpo: String,
    pub alergi: String,
    pub kesadaran: String,
    pub status: String,
    pub td: String,
    pub nadi: String,
    pub suhu: String,
    pub rr: String,
    pub bb: String,
    pub nyeri: String,
    pub gcs: String,
    pub kepala: String,
    pub thoraks: String,
    pub abdomen: String,
    pub muskulos: String,
    pub lainnya: String,
    pub ket_lokalis: String,
    pub lab: String,
    pub rad: String,
    pub pemeriksaan: String,
    pub diagnosis: String,
    pub diagnosis2: String,
    pub permasalahan: String,
    pub terapi: String,
    pub tindakan: String,
    pub edukasi: String,
}

#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct PenilaianMedisJantung {
    pub no_rawat: String,
    pub tanggal: Option<String>,
    pub kd_dokter: String,
    pub anamnesis: String,
    pub hubungan: String,
    pub keluhan_utama: String,
    pub rps: String,
    pub rpd: String,
    pub rpo: String,
    pub alergi: String,
    pub td: String,
    pub bb: String,
    pub tb: String,
    pub suhu: String,
    pub nadi: String,
    pub rr: String,
    pub keadaan_umum: Option<String>,
    pub nyeri: String,
    pub status_nutrisi: String,
    pub jantung: String,
    pub keterangan_jantung: Option<String>,
    pub paru: String,
    pub keterangan_paru: Option<String>,
    pub ekstrimitas: String,
    pub keterangan_ekstrimitas: Option<String>,
    pub lainnya: String,
    pub lab: String,
    pub ekg: String,
    pub penunjang_lain: String,
    pub diagnosis: String,
    pub diagnosis2: String,
    pub permasalahan: String,
    pub terapi: String,
    pub tindakan: String,
    pub edukasi: String,
}

#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct PenilaianMedisBedahMulut {
    pub no_rawat: String,
    pub tanggal: Option<String>,
    pub kd_dokter: String,
    pub anamnesis: String,
    pub hubungan: String,
    pub keluhan_utama: String,
    pub rps: String,
    pub rpd: String,
    pub rpo: String,
    pub alergi: String,
    pub kesadaran: String,
    pub td: String,
    pub nadi: String,
    pub suhu: String,
    pub rr: String,
    pub kepala: String,
    pub keterangan_kepala: String,
    pub mata: String,
    pub keterangan_mata: String,
    pub leher: String,
    pub keterangan_leher: String,
    pub kelenjar: String,
    pub keterangan_kelenjar: String,
    pub dada: String,
    pub keterangan_dada: String,
    pub perut: String,
    pub keterangan_perut: String,
    pub ekstremitas: String,
    pub keterangan_ekstremitas: String,
    pub wajah: String,
    pub intra: String,
    pub gigigeligi: String,
    pub lab: String,
    pub rad: String,
    pub penunjang: String,
    pub diagnosis: String,
    pub diagnosis2: String,
    pub permasalahan: String,
    pub terapi: String,
    pub tindakan: String,
    pub edukasi: String,
}

#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct PenilaianMedisPsikiatrik {
    pub no_rawat: String,
    pub tanggal: Option<String>,
    pub kd_dokter: String,
    pub anamnesis: String,
    pub hubungan: String,
    pub keluhan_utama: String,
    pub rps: String,
    pub rpd: String,
    pub rpo: String,
    pub alergi: String,
    pub penampilan: String,
    pub sikap: String,
    pub mood: String,
    pub fungsi_kognitif: String,
    pub gangguan_persepsi: String,
    pub proses_pikir: String,
    pub pengendalian_impuls: String,
    pub tilikan: String,
    pub rta: String,
    pub keadaan: String,
    pub gcs: String,
    pub kesadaran: String,
    pub td: String,
    pub nadi: String,
    pub rr: String,
    pub suhu: String,
    pub spo: String,
    pub bb: String,
    pub tb: String,
    pub kepala: String,
    pub gigi: String,
    pub tht: String,
    pub thoraks: String,
    pub abdomen: String,
    pub genital: String,
    pub ekstremitas: String,
    pub kulit: String,
    pub ket_fisik: String,
    pub penunjang: String,
    pub diagnosis: String,
    pub tata: String,
    pub konsulrujuk: String,
}

#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct PenilaianMedisOrthopedi {
    pub no_rawat: String,
    pub tanggal: Option<String>,
    pub kd_dokter: String,
    pub anamnesis: String,
    pub hubungan: String,
    pub keluhan_utama: String,
    pub rps: String,
    pub rpd: String,
    pub rpo: String,
    pub alergi: String,
    pub kesadaran: String,
    pub status: String,
    pub td: String,
    pub nadi: String,
    pub suhu: String,
    pub rr: String,
    pub bb: String,
    pub nyeri: String,
    pub gcs: String,
    pub kepala: String,
    pub thoraks: String,
    pub abdomen: String,
    pub ekstremitas: String,
    pub genetalia: String,
    pub columna: String,
    pub muskulos: String,
    pub lainnya: String,
    pub ket_lokalis: String,
    pub lab: String,
    pub rad: String,
    pub pemeriksaan: String,
    pub diagnosis: String,
    pub diagnosis2: String,
    pub permasalahan: String,
    pub terapi: String,
    pub tindakan: String,
    pub edukasi: String,
}

#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct PenilaianMedisUrologi {
    pub no_rawat: String,
    pub tanggal: Option<String>,
    pub kd_dokter: String,
    pub anamnesis: String,
    pub hubungan: String,
    pub keluhan_utama: String,
    pub rps: String,
    pub rpd: String,
    pub rpo: String,
    pub riwayat_kebiasaan: String,
    pub riwayat_operasi_urologi: String,
    pub alergi: String,
    pub td: String,
    pub bb: String,
    pub tb: String,
    pub suhu: String,
    pub nadi: String,
    pub rr: String,
    pub keadaan_umum: Option<String>,
    pub nyeri: String,
    pub status_nutrisi: String,
    pub thoraks: String,
    pub keterangan_thoraks: Option<String>,
    pub abdomen: String,
    pub keterangan_abdomen: Option<String>,
    pub ekstrimitas: String,
    pub keterangan_ekstrimitas: Option<String>,
    pub nyeri_ketok_cva: Option<String>,
    pub genitalia_eksternal: Option<String>,
    pub colok_dubur: Option<String>,
    pub lainnya: String,
    pub urinalisis: String,
    pub darah: String,
    pub usg_urologi: String,
    pub radiologi: String,
    pub penunjang_lain: String,
    pub diagnosis: String,
    pub diagnosis2: String,
    pub permasalahan: String,
    pub terapi: String,
    pub tindakan: String,
    pub edukasi: String,
}
#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct PenilaianMedisGeriatri {
    pub no_rawat: String,
    pub tanggal: Option<String>,
    pub kd_dokter: String,
    pub anamnesis: String,
    pub hubungan: String,
    pub keluhan_utama: String,
    pub rps: String,
    pub rpd: String,
    pub rpo: String,
    pub alergi: String,
    pub kesadaran: String,
    pub td: String,
    pub nadi: String,
    pub suhu: String,
    pub rr: String,
    pub bb: String,
    pub nyeri: String,
    pub gcs: String,
    pub kepala: String,
    pub keterangan_kepala: String,
    pub thoraks: String,
    pub keterangan_thoraks: String,
    pub abdomen: String,
    pub keterangan_abdomen: String,
    pub ekstremitas: String,
    pub keterangan_ekstremitas: String,
    #[sqlx(rename = "Integument_kebersihan")]
    pub integument_kebersihan: String,
    #[sqlx(rename = "Integument_warna")]
    pub integument_warna: String,
    #[sqlx(rename = "Integument_kelembaban")]
    pub integument_kelembaban: String,
    #[sqlx(rename = "Integument_gangguan_kulit")]
    pub integument_gangguan_kulit: String,
    pub status_fungsional: String,
    pub skrining_jatuh: String,
    pub status_nutrisi: String,
    pub lainnya: String,
    pub lab: String,
    pub rad: String,
    pub pemeriksaan: String,
    pub diagnosis: String,
    pub diagnosis2: String,
    pub permasalahan: String,
    pub terapi: String,
    pub tindakan: String,
    pub edukasi: String,
}

#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct PenilaianMedisRehabMedik {
    pub no_rawat: String,
    pub tanggal: Option<String>,
    pub kd_dokter: String,
    pub anamnesis: String,
    pub hubungan: String,
    pub keluhan_utama: String,
    pub rps: String,
    pub rpd: String,
    pub rpo: String,
    pub alergi: String,
    pub kesadaran: String,
    pub td: String,
    pub nadi: String,
    pub suhu: String,
    pub rr: String,
    pub bb: String,
    pub nyeri: String,
    pub gcs: String,
    pub kepala: Option<String>,
    pub keterangan_kepala: Option<String>,
    pub thoraks: Option<String>,
    pub keterangan_thoraks: Option<String>,
    pub abdomen: Option<String>,
    pub keterangan_abdomen: Option<String>,
    pub ekstremitas: Option<String>,
    pub keterangan_ekstremitas: Option<String>,
    pub columna: Option<String>,
    pub keterangan_columna: Option<String>,
    pub muskulos: Option<String>,
    pub keterangan_muskulos: Option<String>,
    pub lainnya: Option<String>,
    pub resiko_jatuh: Option<String>,
    pub resiko_nutrisional: Option<String>,
    pub kebutuhan_fungsional: Option<String>,
    pub diagnosa_medis: Option<String>,
    pub diagnosa_fungsi: Option<String>,
    pub penunjang_lain: Option<String>,
    pub fisio: Option<String>,
    pub okupasi: Option<String>,
    pub wicara: Option<String>,
    pub akupuntur: Option<String>,
    pub tatalain: Option<String>,
    pub frekuensi_terapi: Option<String>,
    pub fisioterapi: Option<String>,
    pub terapi_okupasi: Option<String>,
    pub terapi_wicara: Option<String>,
    pub terapi_akupuntur: Option<String>,
    pub terapi_lainnya: Option<String>,
    pub edukasi: Option<String>,
}

#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct PenilaianMedisKulitKelamin {
    pub no_rawat: String,
    pub tanggal: Option<String>,
    pub kd_dokter: String,
    pub anamnesis: String,
    pub hubungan: String,
    pub keluhan_utama: String,
    pub rps: String,
    pub rpd: String,
    pub rpo: String,
    pub rpk: String,
    pub kesadaran: String,
    pub status: String,
    pub td: String,
    pub nadi: String,
    pub suhu: String,
    pub rr: String,
    pub bb: String,
    pub nyeri: String,
    pub gcs: String,
    pub statusderma: String,
    pub pemeriksaan: String,
    pub diagnosis: String,
    pub diagnosis2: String,
    pub permasalahan: String,
    pub terapi: String,
    pub tindakan: String,
    pub edukasi: String,
}

#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct PenilaianMedisGDPsikiatri {
    pub no_rawat: String,
    pub tanggal: Option<String>,
    pub kd_dokter: String,
    pub anamnesis: String,
    pub hubungan: String,
    pub keluhan_utama: Option<String>,
    pub gejala_menyertai: Option<String>,
    pub faktor_pencetus: Option<String>,
    pub riwayat_penyakit_dahulu: Option<String>,
    pub keterangan_riwayat_penyakit_dahulu: Option<String>,
    pub riwayat_kehamilan: Option<String>,
    pub riwayat_sosial: Option<String>,
    pub keterangan_riwayat_sosial: Option<String>,
    pub riwayat_pekerjaan: Option<String>,
    pub keterangan_riwayat_pekerjaan: Option<String>,
    pub riwayat_obat_diminum: Option<String>,
    pub faktor_kepribadian_premorbid: Option<String>,
    pub faktor_keturunan: Option<String>,
    pub keterangan_faktor_keturunan: Option<String>,
    pub faktor_organik: Option<String>,
    pub keterangan_faktor_organik: Option<String>,
    pub riwayat_alergi: Option<String>,
    pub fisik_kesadaran: Option<String>,
    pub fisik_td: Option<String>,
    pub fisik_rr: Option<String>,
    pub fisik_suhu: Option<String>,
    pub fisik_nyeri: Option<String>,
    pub fisik_nadi: Option<String>,
    pub fisik_bb: Option<String>,
    pub fisik_tb: Option<String>,
    pub fisik_status_nutrisi: Option<String>,
    pub fisik_gcs: Option<String>,
    pub status_kelainan_kepala: Option<String>,
    pub keterangan_status_kelainan_kepala: Option<String>,
    pub status_kelainan_leher: Option<String>,
    pub keterangan_status_kelainan_leher: Option<String>,
    pub status_kelainan_dada: Option<String>,
    pub keterangan_status_kelainan_dada: Option<String>,
    pub status_kelainan_perut: Option<String>,
    pub keterangan_status_kelainan_perut: Option<String>,
    pub status_kelainan_anggota_gerak: Option<String>,
    pub keterangan_status_kelainan_anggota_gerak: Option<String>,
    pub status_lokalisata: Option<String>,
    pub psikiatrik_kesan_umum: Option<String>,
    pub psikiatrik_sikap_prilaku: Option<String>,
    pub psikiatrik_kesadaran: Option<String>,
    pub psikiatrik_orientasi: Option<String>,
    pub psikiatrik_daya_ingat: Option<String>,
    pub psikiatrik_persepsi: Option<String>,
    pub psikiatrik_pikiran: Option<String>,
    pub psikiatrik_insight: Option<String>,
    pub laborat: Option<String>,
    pub radiologi: Option<String>,
    pub ekg: Option<String>,
    pub diagnosis: Option<String>,
    pub permasalahan: Option<String>,
    pub instruksi_medis: Option<String>,
    pub rencana_target: Option<String>,
    pub pulang_dipulangkan: Option<String>,
    pub keterangan_pulang_dipulangkan: Option<String>,
    pub pulang_dirawat_diruang: Option<String>,
    pub pulang_indikasi_ranap: Option<String>,
    pub pulang_dirujuk_ke: Option<String>,
    pub pulang_alasan_dirujuk: Option<String>,
    pub pulang_paksa: Option<String>,
    pub keterangan_pulang_paksa: Option<String>,
    pub pulang_meninggal_igd: Option<String>,
    pub pulang_penyebab_kematian: Option<String>,
    pub fisik_pulang_kesadaran: Option<String>,
    pub fisik_pulang_td: Option<String>,
    pub fisik_pulang_nadi: Option<String>,
    pub fisik_pulang_gcs: Option<String>,
    pub fisik_pulang_suhu: Option<String>,
    pub fisik_pulang_rr: Option<String>,
    pub edukasi: Option<String>,
}

#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct PenilaianPenyakitDalamCustom {
    pub no_rawat: String,
    pub tanggal: Option<String>,
    pub kd_dokter: String,
    pub anamnesis: String,
    pub hubungan: String,
    pub keluhan_utama: String,
    pub rps: String,
    pub rpd: String,
    pub rpo: String,
    pub alergi: String,
    pub kondisi: String,
    pub status: String,
    pub td: String,
    pub nadi: String,
    pub suhu: String,
    pub rr: String,
    pub bb: String,
    pub nyeri: String,
    pub gcs: String,
    pub kepala: String,
    pub keterangan_kepala: String,
    pub thoraks: String,
    pub keterangan_thorak: String,
    pub abdomen: String,
    pub keterangan_abdomen: String,
    pub ekstremitas: String,
    pub keterangan_ekstremitas: String,
    pub lainnya: String,
    pub lab: String,
    pub rad: String,
    pub penunjanglain: String,
    pub diagnosis: String,
    pub diagnosis2: String,
    pub permasalahan: String,
    pub terapi: String,
    pub tindakan: String,
    pub edukasi: String,
}
#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct DataTriaseIgd {
    pub no_rawat: String,
    pub tgl_kunjungan: Option<String>,
    pub cara_masuk: String,
    pub alat_transportasi: String,
    pub alasan_kedatangan: String,
    pub keterangan_kedatangan: String,
    pub kode_kasus: String,
    pub tekanan_darah: String,
    pub nadi: String,
    pub pernapasan: String,
    pub suhu: String,
    pub saturasi_o2: String,
    pub nyeri: String,
}

#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct DataTriaseIgdPrimer {
    pub no_rawat: String,
    pub keluhan_utama: String,
    pub kebutuhan_khusus: String,
    pub catatan: String,
    pub plan: String,
    pub tanggaltriase: chrono::NaiveDateTime,
    pub nik: String,
}

#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct DataTriaseIgdSekunder {
    pub no_rawat: String,
    pub anamnesa_singkat: String,
    pub catatan: String,
    pub plan: String,
    pub tanggaltriase: chrono::NaiveDateTime,
    pub nik: String,
}

#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct PenilaianMedisIgd {
    pub no_rawat: String,
    pub tanggal: Option<String>,
    pub kd_dokter: String,
    pub anamnesis: String,
    pub hubungan: String,
    pub keluhan_utama: String,
    pub rps: String,
    pub rpd: String,
    pub rpk: String,
    pub rpo: String,
    pub alergi: String,
    pub keadaan: String,
    pub gcs: String,
    pub kesadaran: String,
    pub td: String,
    pub nadi: String,
    pub rr: String,
    pub suhu: String,
    pub spo: String,
    pub bb: String,
    pub tb: String,
    pub kepala: String,
    pub mata: String,
    pub gigi: String,
    pub leher: String,
    pub thoraks: String,
    pub abdomen: String,
    pub genital: String,
    pub ekstremitas: String,
    pub ket_fisik: String,
    pub ket_lokalis: String,
    pub ekg: String,
    pub rad: String,
    pub lab: String,
    pub diagnosis: String,
    pub tata: String,
}

#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct TriageRequest {
    pub data: DataTriaseIgd,
    pub primer: Option<DataTriaseIgdPrimer>,
    pub sekunder: Option<DataTriaseIgdSekunder>,
    pub skala1: Vec<String>,
    pub skala2: Vec<String>,
    pub skala3: Vec<String>,
    pub skala4: Vec<String>,
    pub skala5: Vec<String>,
}
